// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvKtuwxEy22z5kuiQGqZ6bAg2GXtSzyUQ',
    appId: '1:203828984200:web:9c6b53a3abec96cff4e23d',
    messagingSenderId: '203828984200',
    projectId: 'tdk2610-game-collection',
    authDomain: 'tdk2610-game-collection.firebaseapp.com',
    storageBucket: 'tdk2610-game-collection.appspot.com',
    measurementId: 'G-Q6Q39504Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUneo2pGhUxWYXH-4eYhWLV48cpNBIFr8',
    appId: '1:203828984200:android:754e62140b3b0caef4e23d',
    messagingSenderId: '203828984200',
    projectId: 'tdk2610-game-collection',
    storageBucket: 'tdk2610-game-collection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1-HxynlJNFU1iEDDW8qBnWU6yrsdTZZg',
    appId: '1:203828984200:ios:4e39bcb491a5aee6f4e23d',
    messagingSenderId: '203828984200',
    projectId: 'tdk2610-game-collection',
    storageBucket: 'tdk2610-game-collection.appspot.com',
    iosBundleId: 'com.example.cardTikimonCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1-HxynlJNFU1iEDDW8qBnWU6yrsdTZZg',
    appId: '1:203828984200:ios:4e39bcb491a5aee6f4e23d',
    messagingSenderId: '203828984200',
    projectId: 'tdk2610-game-collection',
    storageBucket: 'tdk2610-game-collection.appspot.com',
    iosBundleId: 'com.example.cardTikimonCollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvKtuwxEy22z5kuiQGqZ6bAg2GXtSzyUQ',
    appId: '1:203828984200:web:b72ffa02519168a2f4e23d',
    messagingSenderId: '203828984200',
    projectId: 'tdk2610-game-collection',
    authDomain: 'tdk2610-game-collection.firebaseapp.com',
    storageBucket: 'tdk2610-game-collection.appspot.com',
    measurementId: 'G-ZVLYSXWY2Y',
  );
}
